config/routes.rb
Rails.application.routes.draw do
  resources :pelis

end

app/models/peli.rb
class Peli < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pelis_controller.rb
class PelisController < ApplicationController
  before_action :set_peli, only: [:show, :edit, :update, :destroy]

  # GET /pelis
  # GET /pelis.json
  def index
    @pelis = Peli.all
  end

  # GET /pelis/1
  # GET /pelis/1.json
  def show
  end

  # GET /pelis/new
  def new
    @peli = Peli.new
  end

  # GET /pelis/1/edit
  def edit
  end

  # POST /pelis
  # POST /pelis.json
  def create
    @peli = Peli.new(peli_params)

    respond_to do |format|
      if @peli.save
        format.html { redirect_to @peli, notice: 'Peli was successfully created.' }
        format.json { render :show, status: :created, location: @peli }
      else
        format.html { render :new }
        format.json { render json: @peli.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pelis/1
  # PATCH/PUT /pelis/1.json
  def update
    respond_to do |format|
      if @peli.update(peli_params)
        format.html { redirect_to @peli, notice: 'Peli was successfully updated.' }
        format.json { render :show, status: :ok, location: @peli }
      else
        format.html { render :edit }
        format.json { render json: @peli.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pelis/1
  # DELETE /pelis/1.json
  def destroy
    @peli.destroy
    respond_to do |format|
      format.html { redirect_to pelis_url, notice: 'Peli was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_peli
      @peli = Peli.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def peli_params
      params.require(:peli).permit(:Nombre, :Director, :Anio)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pelis_helper.rb
module PelisHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Movies</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pelis/_form.html.erb
<%= form_for(@peli) do |f| %>
  <% if @peli.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@peli.errors.count, "error") %> prohibited this peli from being saved:</h2>

      <ul>
      <% @peli.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Nombre %><br>
    <%= f.text_field :Nombre %>
  </div>
  <div class="field">
    <%= f.label :Director %><br>
    <%= f.text_field :Director %>
  </div>
  <div class="field">
    <%= f.label :Anio %><br>
    <%= f.text_field :Anio %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pelis/edit.html.erb
<h1>Editing Peli</h1>

<%= render 'form' %>

<%= link_to 'Show', @peli %> |
<%= link_to 'Back', pelis_path %>

app/views/pelis/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pelis</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Director</th>
      <th>Anio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pelis.each do |peli| %>
      <tr>
        <td><%= peli.Nombre %></td>
        <td><%= peli.Director %></td>
        <td><%= peli.Anio %></td>
        <td><%= link_to 'Show', peli %></td>
        <td><%= link_to 'Edit', edit_peli_path(peli) %></td>
        <td><%= link_to 'Destroy', peli, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Peli', new_peli_path %>

app/views/pelis/new.html.erb
<h1>New Peli</h1>

<%= render 'form' %>

<%= link_to 'Back', pelis_path %>

app/views/pelis/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @peli.Nombre %>
</p>

<p>
  <strong>Director:</strong>
  <%= @peli.Director %>
</p>

<p>
  <strong>Anio:</strong>
  <%= @peli.Anio %>
</p>

<%= link_to 'Edit', edit_peli_path(@peli) %> |
<%= link_to 'Back', pelis_path %>